"""
Formal spec format for the arena allocator domain.

This is the structured intermediate representation between
natural language intent and verified code generation.
An AI generates these specs; a human never writes them directly.
"""

from dataclasses import dataclass, field
from enum import Enum
from typing import Optional


class ThreadSafety(Enum):
    SINGLE_THREADED = "single_threaded"
    THREAD_LOCAL = "thread_local"
    LOCK_FREE = "lock_free"


class AllocStrategy(Enum):
    BUMP = "bump"           # Linear bump pointer, O(1) alloc
    POOL = "pool"           # Fixed-size block pool
    FREELIST = "freelist"   # Free list with coalescing


class GrowthPolicy(Enum):
    FIXED = "fixed"         # Single arena, no growth
    CHAIN = "chain"         # Chain new arenas when full
    DOUBLE = "double"       # Double arena size on growth


@dataclass
class AlignmentSpec:
    min_align: int = 8          # Minimum alignment in bytes
    max_align: int = 64         # Maximum alignment supported
    natural_align: bool = True  # Align to type's natural alignment


@dataclass
class MemoryBounds:
    page_size: int = 4096           # Arena page size in bytes
    max_pages: int = 1              # Maximum number of pages
    max_alloc_size: int = 0         # Max single allocation (0 = page_size - header)
    header_size: int = 16           # Per-arena metadata overhead

    @property
    def total_capacity(self) -> int:
        return self.page_size * self.max_pages

    @property
    def usable_capacity(self) -> int:
        return self.total_capacity - (self.header_size * self.max_pages)

    @property
    def effective_max_alloc(self) -> int:
        if self.max_alloc_size > 0:
            return self.max_alloc_size
        return self.page_size - self.header_size


@dataclass
class SafetyInvariants:
    no_overflow: bool = True            # Bump pointer never exceeds arena bounds
    aligned_allocs: bool = True         # All returned pointers are aligned
    bounded_memory: bool = True         # Total memory usage is provably bounded
    no_use_after_reset: bool = False    # Prevent use-after-free (requires generation tracking)
    zero_on_alloc: bool = False         # Zero memory on allocation
    zero_on_reset: bool = False         # Zero memory on reset (security)


@dataclass
class PerformanceConstraints:
    alloc_time_ns: Optional[int] = None     # Max allocation time in ns
    reset_time_ns: Optional[int] = None     # Max reset time in ns
    cache_line_size: int = 64               # Target cache line size


@dataclass
class ArenaSpec:
    """
    Complete formal specification for an arena allocator.

    Generated by AI from natural language intent.
    Verified by Z3 before code generation.
    """
    name: str = "arena"

    strategy: AllocStrategy = AllocStrategy.BUMP
    growth: GrowthPolicy = GrowthPolicy.FIXED
    thread_safety: ThreadSafety = ThreadSafety.SINGLE_THREADED

    memory: MemoryBounds = field(default_factory=MemoryBounds)
    alignment: AlignmentSpec = field(default_factory=AlignmentSpec)
    safety: SafetyInvariants = field(default_factory=SafetyInvariants)
    performance: PerformanceConstraints = field(default_factory=PerformanceConstraints)

    def describe(self) -> str:
        """Human-readable summary of the spec."""
        lines = [
            f"Arena Allocator Spec: {self.name}",
            f"  Strategy: {self.strategy.value}",
            f"  Growth: {self.growth.value}",
            f"  Threading: {self.thread_safety.value}",
            f"  Page size: {self.memory.page_size} bytes",
            f"  Max pages: {self.memory.max_pages}",
            f"  Total capacity: {self.memory.total_capacity} bytes",
            f"  Usable capacity: {self.memory.usable_capacity} bytes",
            f"  Max single alloc: {self.memory.effective_max_alloc} bytes",
            f"  Alignment: {self.alignment.min_align}-{self.alignment.max_align} bytes",
            f"  Safety: " + ", ".join(
                k for k, v in vars(self.safety).items() if v
            ),
        ]
        return "\n".join(lines)
