/*
 * Auto-generated arena allocator: lockfree_arena
 *
 * Strategy:    freelist
 * Page size:   4096 bytes
 * Max pages:   256
 * Alignment:   64 bytes
 * Threading:   lock_free
 *
 * VERIFIED PROPERTIES:
 *   - Bump pointer cannot overflow when space available
 *   - All allocations are 64-byte aligned
 *   - Total memory bounded at 1048576 bytes
 *
 * Generated by prompt2bin — do not edit manually.
 */

#ifndef LOCKFREE_ARENA_H
#define LOCKFREE_ARENA_H

#include <stddef.h>
#include <stdint.h>
#include <stdlib.h>
#include <stdatomic.h>


typedef struct {
    uint8_t *buf;       /* backing memory */
    atomic_size_t offset;  /* current bump pointer offset */
    size_t capacity;    /* usable capacity (page_size - header) */
} lockfree_arena_t;


lockfree_arena_t *lockfree_arena_create(void) {
    /* Allocate arena struct + backing buffer in a single allocation
     * to minimize fragmentation and ensure locality. */
    size_t total = sizeof(lockfree_arena_t) + 4096;

    /* aligned_alloc requires size to be a multiple of alignment */
    size_t alloc_size = (total + 63) & ~(size_t)63;
    void *mem = aligned_alloc(64, alloc_size);
    if (!mem) return NULL;

    lockfree_arena_t *arena = (lockfree_arena_t *)mem;
    arena->buf = (uint8_t *)mem + sizeof(lockfree_arena_t);

    /* Ensure buf is aligned — adjust if struct size isn't a multiple of alignment */
    uintptr_t buf_addr = (uintptr_t)arena->buf;
    buf_addr = (buf_addr + 63) & ~(uintptr_t)63;
    arena->buf = (uint8_t *)buf_addr;

    arena->offset = 0;
    arena->capacity = 4080;

    return arena;
}


void *lockfree_arena_alloc(lockfree_arena_t *arena, size_t size) {
    if (size == 0 || size > 256) return NULL;

    size_t current, aligned, new_offset;
    do {
        current = atomic_load_explicit(&arena->offset, memory_order_relaxed);
        aligned = (current + 63) & ~(size_t)63;
        new_offset = aligned + size;
        if (new_offset > arena->capacity) return NULL;
    } while (!atomic_compare_exchange_weak_explicit(
        &arena->offset, &current, new_offset,
        memory_order_release, memory_order_relaxed));

    return arena->buf + aligned;
}


void lockfree_arena_reset(lockfree_arena_t *arena) {
    atomic_store_explicit(&arena->offset, 0, memory_order_release);
}

void lockfree_arena_destroy(lockfree_arena_t *arena) {
    if (arena) free(arena);
}

#endif /* LOCKFREE_ARENA_H */
