/*
 * Auto-generated arena allocator: key_material_arena
 *
 * Strategy:    bump
 * Page size:   512 bytes
 * Max pages:   1
 * Alignment:   16 bytes
 * Threading:   single_threaded
 *
 * VERIFIED PROPERTIES:
 *   - Bump pointer cannot overflow when space available
 *   - All allocations are 16-byte aligned
 *   - Total memory bounded at 512 bytes
 *
 * Generated by prompt2bin — do not edit manually.
 */

#ifndef KEY_MATERIAL_ARENA_H
#define KEY_MATERIAL_ARENA_H

#include <stddef.h>
#include <stdint.h>
#include <stdlib.h>
#include <string.h>


typedef struct {
    uint8_t *buf;       /* backing memory */
    size_t offset;  /* current bump pointer offset */
    size_t capacity;    /* usable capacity (page_size - header) */
    uint64_t generation; /* generation counter for use-after-reset detection */
} key_material_arena_t;


key_material_arena_t *key_material_arena_create(void) {
    /* Allocate arena struct + backing buffer in a single allocation
     * to minimize fragmentation and ensure locality. */
    size_t total = sizeof(key_material_arena_t) + 512;

    /* aligned_alloc requires size to be a multiple of alignment */
    size_t alloc_size = (total + 15) & ~(size_t)15;
    void *mem = aligned_alloc(16, alloc_size);
    if (!mem) return NULL;

    key_material_arena_t *arena = (key_material_arena_t *)mem;
    arena->buf = (uint8_t *)mem + sizeof(key_material_arena_t);

    /* Ensure buf is aligned — adjust if struct size isn't a multiple of alignment */
    uintptr_t buf_addr = (uintptr_t)arena->buf;
    buf_addr = (buf_addr + 15) & ~(uintptr_t)15;
    arena->buf = (uint8_t *)buf_addr;

    arena->offset = 0;
    arena->capacity = 496;
    arena->generation = 0;
    return arena;
}


void *key_material_arena_alloc(key_material_arena_t *arena, size_t size) {
    if (size == 0 || size > 496) return NULL;

    /* Round offset up to 16-byte alignment — verified by Z3:
     * for any aligned base and any offset, (offset + mask) & ~mask
     * produces an aligned result. */
    size_t aligned_offset = (arena->offset + 15) & ~(size_t)15;

    /* Bounds check — verified by Z3: if this check passes,
     * aligned_offset + size cannot overflow. */
    if (aligned_offset + size > arena->capacity) return NULL;

    void *ptr = arena->buf + aligned_offset;
    arena->offset = aligned_offset + size;
    memset(ptr, 0, size);
    return ptr;
}


void key_material_arena_reset(key_material_arena_t *arena) {
    memset(arena->buf, 0, arena->offset);
    arena->offset = 0;
    arena->generation++;
}

void key_material_arena_destroy(key_material_arena_t *arena) {
    if (arena) free(arena);
}

#endif /* KEY_MATERIAL_ARENA_H */
