/*
 * Auto-generated arena allocator: frame_scratch
 *
 * Strategy:    bump
 * Page size:   65536 bytes
 * Max pages:   1
 * Alignment:   8 bytes
 * Threading:   single_threaded
 *
 * VERIFIED PROPERTIES:
 *   - Bump pointer cannot overflow when space available
 *   - All allocations are 8-byte aligned
 *   - Total memory bounded at 65536 bytes
 *
 * Generated by prompt2bin — do not edit manually.
 */

#ifndef FRAME_SCRATCH_H
#define FRAME_SCRATCH_H

#include <stddef.h>
#include <stdint.h>
#include <stdlib.h>


typedef struct {
    uint8_t *buf;       /* backing memory */
    size_t offset;  /* current bump pointer offset */
    size_t capacity;    /* usable capacity (page_size - header) */
    uint64_t generation; /* generation counter for use-after-reset detection */
} frame_scratch_t;


frame_scratch_t *frame_scratch_create(void) {
    /* Allocate arena struct + backing buffer in a single allocation
     * to minimize fragmentation and ensure locality. */
    size_t total = sizeof(frame_scratch_t) + 65536;

    /* aligned_alloc requires size to be a multiple of alignment */
    size_t alloc_size = (total + 7) & ~(size_t)7;
    void *mem = aligned_alloc(8, alloc_size);
    if (!mem) return NULL;

    frame_scratch_t *arena = (frame_scratch_t *)mem;
    arena->buf = (uint8_t *)mem + sizeof(frame_scratch_t);

    /* Ensure buf is aligned — adjust if struct size isn't a multiple of alignment */
    uintptr_t buf_addr = (uintptr_t)arena->buf;
    buf_addr = (buf_addr + 7) & ~(uintptr_t)7;
    arena->buf = (uint8_t *)buf_addr;

    arena->offset = 0;
    arena->capacity = 65520;
    arena->generation = 0;
    return arena;
}


void *frame_scratch_alloc(frame_scratch_t *arena, size_t size) {
    if (size == 0 || size > 65520) return NULL;

    /* Round offset up to 8-byte alignment — verified by Z3:
     * for any aligned base and any offset, (offset + mask) & ~mask
     * produces an aligned result. */
    size_t aligned_offset = (arena->offset + 7) & ~(size_t)7;

    /* Bounds check — verified by Z3: if this check passes,
     * aligned_offset + size cannot overflow. */
    if (aligned_offset + size > arena->capacity) return NULL;

    void *ptr = arena->buf + aligned_offset;
    arena->offset = aligned_offset + size;
    return ptr;
}


void frame_scratch_reset(frame_scratch_t *arena) {
    arena->offset = 0;
    arena->generation++;
}

void frame_scratch_destroy(frame_scratch_t *arena) {
    if (arena) free(arena);
}

#endif /* FRAME_SCRATCH_H */
