/*
 * Auto-generated arena allocator: game_frame
 *
 * Strategy:    bump
 * Page size:   65536 bytes
 * Max pages:   1
 * Alignment:   16 bytes
 * Threading:   single_threaded
 *
 * VERIFIED PROPERTIES:
 *   - Bump pointer cannot overflow when space available
 *   - All allocations are 16-byte aligned
 *   - Total memory bounded at 65536 bytes
 *
 * Generated by prompt2bin — do not edit manually.
 */

#ifndef GAME_FRAME_H
#define GAME_FRAME_H

#include <stddef.h>
#include <stdint.h>
#include <stdlib.h>


typedef struct {
    uint8_t *buf;       /* backing memory */
    size_t offset;  /* current bump pointer offset */
    size_t capacity;    /* usable capacity (page_size - header) */
    uint64_t generation; /* generation counter for use-after-reset detection */
} game_frame_t;


game_frame_t *game_frame_create(void) {
    /* Allocate arena struct + backing buffer in a single allocation
     * to minimize fragmentation and ensure locality. */
    size_t total = sizeof(game_frame_t) + 65536;

    /* aligned_alloc requires size to be a multiple of alignment */
    size_t alloc_size = (total + 15) & ~(size_t)15;
    void *mem = aligned_alloc(16, alloc_size);
    if (!mem) return NULL;

    game_frame_t *arena = (game_frame_t *)mem;
    arena->buf = (uint8_t *)mem + sizeof(game_frame_t);

    /* Ensure buf is aligned — adjust if struct size isn't a multiple of alignment */
    uintptr_t buf_addr = (uintptr_t)arena->buf;
    buf_addr = (buf_addr + 15) & ~(uintptr_t)15;
    arena->buf = (uint8_t *)buf_addr;

    arena->offset = 0;
    arena->capacity = 65520;
    arena->generation = 0;
    return arena;
}


void *game_frame_alloc(game_frame_t *arena, size_t size) {
    if (size == 0 || size > 65520) return NULL;

    /* Round offset up to 16-byte alignment — verified by Z3:
     * for any aligned base and any offset, (offset + mask) & ~mask
     * produces an aligned result. */
    size_t aligned_offset = (arena->offset + 15) & ~(size_t)15;

    /* Bounds check — verified by Z3: if this check passes,
     * aligned_offset + size cannot overflow. */
    if (aligned_offset + size > arena->capacity) return NULL;

    void *ptr = arena->buf + aligned_offset;
    arena->offset = aligned_offset + size;
    return ptr;
}


void game_frame_reset(game_frame_t *arena) {
    arena->offset = 0;
    arena->generation++;
}

void game_frame_destroy(game_frame_t *arena) {
    if (arena) free(arena);
}

#endif /* GAME_FRAME_H */
